In [1]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np

arr = np.arange(6)
print(arr)
print("Data type:", arr.dtype)


[0 1 2 3 4 5]
Data type: int64


In [2]:
#2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
if arr.dtype == np.float64:
    print("The array data type is float64.")
else:
    print("The array data type is not float64.")


The array data type is float64.


In [3]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)
print("Data type:", arr.dtype)


[1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


In [4]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)
print(arr_float32)
print("Data type:", arr_float32.dtype)


[1. 2. 3. 4. 5.]
Data type: float32


In [5]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)
print("Data type:", arr_float32.dtype)


[1.1 2.2 3.3]
Data type: float32


In [6]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
#ype.
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([[1, 2], [3, 4]])
print(array_attributes(arr))


((2, 2), 4, dtype('int64'))


In [7]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality
def array_dimension(arr):
    return arr.ndim

arr = np.array([1, 2, 3])
print(array_dimension(arr))


1


In [8]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
#size in bytes.
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr = np.array([1, 2, 3, 4])
print(item_size_info(arr))


(8, 32)


In [9]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array
def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_strides(arr))


(24, 8)


In [10]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
#and strides of the array.
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1, 2], [3, 4]])
print(shape_stride_relationship(arr))


((2, 2), (16, 8))


In [11]:
#11. Create a function create_zeros_array that takes an integer n as input and returns a NumPy array of
#zeros with n elements.
def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))

[0. 0. 0. 0. 0.]


In [12]:
#12. Write a function create_ones_matrix that takes integers rows and cols as inputs and generates a 2D
#NumPy array filled with ones of size rows x cols.


In [13]:
'''#13. Write a function generate_range_array that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from start, ending at stop (exclusive), and with the specified
step.'''
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(0, 10, 2))



[0 2 4 6 8]


In [14]:
'''14. Design a function generate_linear_space that takes two floats start, stop, and an integer num as
arguments and generates a NumPy array with num equally spaced values between start and stop
(inclusive).'''
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_linear_space(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


In [15]:
'''15. Create a function create_identity_matrix that takes an integer n as input and generates a square
identity matrix of size n x n using numpy.eye.'''
def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
'''16. Write a function that takes a Python list and converts it into a NumPy array.'''
def list_to_numpy(lst):
    return np.array(lst)

print(list_to_numpy([1, 2, 3, 4]))



[1 2 3 4]


In [17]:
'''17. Create a NumPy array and demonstrate the use of numpy.view to create a new array object with the
same data.'''
arr = np.array([1, 2, 3, 4, 5])
arr_view = arr.view()
arr_view[0] = 100

print("Original array:", arr)
print("View of array:", arr_view)


Original array: [100   2   3   4   5]
View of array: [100   2   3   4   5]


In [18]:
'''18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.'''
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(arr1, arr2, axis=0))  # Vertical concatenation
print(concatenate_arrays(arr1, arr2, axis=1))  # Horizontal concatenation


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [21]:
'''19. Create two NumPy arrays with different shapes and concatenate them horizontally using numpy.concatenate.'''
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])
result = np.concatenate((arr1, arr2), axis=1)
print(result)


[[1 2 5]
 [3 4 6]]


In [22]:
'''20. Write a function that vertically stacks multiple NumPy arrays given as a list.'''
def vertical_stack(arr_list):
    return np.vstack(arr_list)

arr_list = [np.array([1, 2]), np.array([3, 4]), np.array([5, 6])]
print(vertical_stack(arr_list))


[[1 2]
 [3 4]
 [5 6]]


In [23]:
'''21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.'''
def create_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

print(create_range_array(1, 10, 2))


[1 3 5 7 9]


In [24]:
'''22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).'''
def generate_equally_spaced():
    return np.linspace(0, 1, 10)

print(generate_equally_spaced())


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [25]:
'''23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).'''
def generate_log_space():
    return np.logspace(0, 3, 5)

print(generate_log_space())


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [26]:
'''24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.'''
import pandas as pd

def create_dataframe():
    data = np.random.randint(1, 101, size=(5, 3))
    return pd.DataFrame(data, columns=['A', 'B', 'C'])

print(create_dataframe())


    A    B   C
0  70   41  26
1  88   49  86
2  90  100  46
3  88   24  10
4  26   62  97


In [27]:
'''25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.'''
def replace_negatives(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

df = pd.DataFrame({'A': [1, -2, 3], 'B': [-4, 5, -6]})
print(replace_negatives(df, 'A'))


   A  B
0  1 -4
1  0  5
2  3 -6


In [28]:
'''26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])'''
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])  # Index 2 corresponds to the 3rd element


30


In [29]:
'''27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])'''
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2])  # Row 1, Column 2


6


In [30]:
'''28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
'''
arr = np.array([3, 8, 2, 10, 5, 7])
print(arr[arr > 5])


[ 8 10  7]


In [31]:
'''29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])'''
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:6])  # Extract indices 2, 3, 4, 5


[3 4 5 6]


In [32]:
'''30. Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array.
arr = np.array([10, 20, 30, 40, 50])
arr = np.array([3, 8, 2, 10, 5, 7])
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
'''
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]  # Rows 0 to 1, Columns 1 to 2
print(sub_array)


[[2 3]
 [5 6]]


In [33]:
'''31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array'''
def extract_elements(arr, indices):
    return arr[indices[:, 0], indices[:, 1]]

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 2], [1, 1], [2, 0]])
print(extract_elements(arr, indices))  # Output: [3, 5, 7]


[3 5 7]


In [34]:
'''32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.'''
def filter_elements(arr, threshold):
    return arr[arr > threshold]

arr = np.array([1, 5, 8, 3, 10, 2])
print(filter_elements(arr, 5))  # Output: [8, 10]


[ 8 10]


In [35]:
'''33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.'''
def extract_from_3d(arr, x_idx, y_idx, z_idx):
    return arr[x_idx, y_idx, z_idx]

arr = np.random.randint(1, 10, (3, 3, 3))
x_idx = np.array([0, 1, 2])
y_idx = np.array([1, 2, 0])
z_idx = np.array([2, 0, 1])
print(extract_from_3d(arr, x_idx, y_idx, z_idx))


[2 4 1]


In [36]:
'''34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.'''
def filter_conditions(arr, cond1, cond2):
    return arr[(arr > cond1) & (arr < cond2)]

arr = np.array([1, 5, 8, 3, 10, 2])
print(filter_conditions(arr, 3, 9))  # Output: [5, 8]


[5 8]


In [37]:
'''35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.'''
def extract_using_indices(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])
print(extract_using_indices(arr, row_indices, col_indices))  # Output: [3, 5, 7]


[3 5 7]


In [38]:
'''36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.'''
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr += 5
print(arr)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [39]:
'''37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.'''
arr1 = np.array([[1, 2, 3]])
arr2 = np.random.randint(1, 10, (3, 4))
result = arr1.T * arr2
print(result)


[[ 8  2  6  2]
 [18  2  4 18]
 [27  3 21  3]]


In [40]:
'''38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.'''
arr1 = np.array([1, 2, 3, 4])
arr2 = np.random.randint(1, 10, (4, 3))
result = arr2 + arr1[:, np.newaxis]
print(result)


[[ 2  5  2]
 [ 6  6  6]
 [ 9  9  4]
 [ 6 11 12]]


In [41]:
'''39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.'''
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
result = arr1 + arr2
print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [42]:
'''40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.'''
arr1 = np.random.randint(1, 5, (2, 3))
arr2 = np.random.randint(1, 5, (2, 2))
try:
    result = arr1 * arr2
except ValueError as e:
    print(f"Shape mismatch error: {e}")


Shape mismatch error: operands could not be broadcast together with shapes (2,3) (2,2) 


In [43]:
'''41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])'''
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean = np.mean(arr, axis=0)
print(column_mean)  # Output: [2.5, 3.5, 4.5]


[2.5 3.5 4.5]


In [44]:
'''42. Find maximum value in each row of the given array:arr = np.array([[1, 2, 3], [4, 5, 6]])'''
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = np.max(arr, axis=1)
print(row_max)  # Output: [3, 6]


[3 6]


In [45]:
'''43. For the given array, find indices of maximum value in each column. arr = np.array([[1, 2, 3], [4, 5, 6]])'''
arr = np.array([[1, 2, 3], [4, 5, 6]])
col_max_indices = np.argmax(arr, axis=0)
print(col_max_indices)  # Output: [1, 1, 1]


[1 1 1]


In [46]:
'''44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])'''
def moving_sum(arr, window):
    return np.array([np.convolve(row, np.ones(window, dtype=int), 'valid') for row in arr])

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(moving_sum(arr, window=2))  # Output: [[3, 5], [9, 11]]


[[ 3  5]
 [ 9 11]]


In [47]:
'''45. In the given array, check if all elements in each column are even.arr = np.array([[2, 4, 6], [3, 5, 7]])'''
arr = np.array([[2, 4, 6], [3, 5, 7]])
col_all_even = np.all(arr % 2 == 0, axis=0)
print(col_all_even)  # Output: [False, False, False]


[False False False]


In [48]:
'''46. Given a NumPy array arr, reshape it into a matrix of dimensions m rows and n columns. Return the
reshaped matrix.original_array = np.array([1, 2, 3, 4, 5, 6])'''
def reshape_array(arr, m, n):
    return arr.reshape((m, n))

original_array = np.array([1, 2, 3, 4, 5, 6])
print(reshape_array(original_array, 2, 3))  # Output: [[1, 2, 3], [4, 5, 6]]


[[1 2 3]
 [4 5 6]]


In [49]:
'''47. Create a function that takes a matrix as input and returns the flattened array.input_matrix = np.array([[1, 2, 3], [4, 5, 6]])'''
def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(flatten_matrix(input_matrix))  # Output: [1, 2, 3, 4, 5, 6]


[1 2 3 4 5 6]


In [50]:
'''48. Write a function that concatenates two given arrays along a specified axis.array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]]) '''
def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(array1, array2, axis=0))  # Output: Vertical concatenation
print(concatenate_arrays(array1, array2, axis=1))  # Output: Horizontal concatenation


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [51]:
'''49. Create a function that splits an array into multiple sub-arrays along a specified axis.original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])'''
def split_array(arr, sections, axis):
    return np.array_split(arr, sections, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(split_array(original_array, 3, axis=0))  # Output: Split along rows


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [52]:
'''50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3] '''
def modify_array(arr, indices_insert, values_insert, indices_delete):
    arr = np.insert(arr, indices_insert, values_insert)
    arr = np.delete(arr, indices_delete)
    return arr

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
print(modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete))
# Output: [ 1  3 10 11  5]


[ 1 10  4 11  5]


In [53]:
'''51. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 10.
Perform element-wise addition between arr1 and arr2.'''
arr1 = np.random.randint(1, 10, 10)
arr2 = np.arange(1, 11)
print(arr1 + arr2)


[ 6  9  4  6  8 15 13 16 12 12]


In [54]:
'''52. Generate a NumPy array arr1 with sequential integers from 10 to 1 and another array arr2 with integers
from 1 to 10. Subtract arr2 from arr1 element-wise.'''
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
print(arr1 - arr2)


[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [55]:
'''53. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 5.
Perform element-wise multiplication between arr1 and arr2.'''
arr1 = np.random.randint(1, 10, 10)
arr2 = np.arange(1, 6)
print(arr1[:5] * arr2)


[ 3 12 27 32 10]


In [56]:
'''54. Generate a NumPy array arr1 with even integers from 2 to 10 and another array arr2 with integers from 1
to 5. Perform element-wise division of arr1 by arr2.'''
arr1 = np.arange(2, 12, 2)
arr2 = np.arange(1, 6)
print(arr1 / arr2)


[2. 2. 2. 2. 2.]


In [57]:
'''55. Create a NumPy array arr1 with integers from 1 to 5 and another array arr2 with the same numbers
reversed. Calculate the exponentiation of arr1 raised to the power of arr2 element-wise.'''
arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
print(arr1 ** arr2)  # Output: [  1  16  27  16   5]


[ 1 16 27 16  5]


In [58]:
'''56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])'''
def count_substring(arr, substring):
    return np.char.count(arr, substring).sum()

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
print(count_substring(arr, 'hello'))  # Output: 3


3


In [59]:
'''57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])'''
def extract_uppercase(arr):
    return np.array([''.join([char for char in string if char.isupper()]) for string in arr])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
print(extract_uppercase(arr))  # Output: ['H' 'W' 'OA' 'GPT']


['H' 'W' 'OAI' 'GPT']


In [60]:
'''58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string. arr = np.array(['apple', 'banana', 'grape', 'pineapple']) '''
def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(replace_substring(arr, 'apple', 'orange'))  # Output: ['orange' 'banana' 'grape' 'pineorange']


['orange' 'banana' 'grape' 'pineorange']


In [61]:
'''59. Write a function that concatenates strings in a NumPy array element-wise.arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI']) '''
def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
print(concatenate_strings(arr1, arr2))  # Output: ['HelloOpen' 'WorldAI']


['HelloOpen' 'WorldAI']


In [62]:
'''60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])'''
def find_longest_string_length(arr):
    return max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(find_longest_string_length(arr))  # Output: 9


9


In [63]:
'''61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.'''
data = np.random.randint(1, 1001, 100)
print(f"Mean: {np.mean(data)}")
print(f"Median: {np.median(data)}")
print(f"Variance: {np.var(data)}")
print(f"Standard Deviation: {np.std(data)}")


Mean: 505.12
Median: 519.0
Variance: 85258.58559999999
Standard Deviation: 291.9907286199341


In [64]:
'''62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.'''
data = np.random.randint(1, 101, 50)
print(f"25th Percentile: {np.percentile(data, 25)}")
print(f"75th Percentile: {np.percentile(data, 75)}")


25th Percentile: 22.25
75th Percentile: 75.75


In [65]:
'''63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's corrcoef function'''
arr1 = np.random.rand(50)
arr2 = np.random.rand(50)
print(np.corrcoef(arr1, arr2))


[[ 1.         -0.09450008]
 [-0.09450008  1.        ]]


In [66]:
'''64. Create two matrices and perform matrix multiplication using NumPy's dot function.'''
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(np.dot(matrix1, matrix2))


[[19 22]
 [43 50]]


In [67]:
'''65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.'''
data = np.random.randint(10, 1001, 50)
print(f"10th Percentile: {np.percentile(data, 10)}")
print(f"50th Percentile (Median): {np.percentile(data, 50)}")
print(f"90th Percentile: {np.percentile(data, 90)}")
print(f"First Quartile (25th Percentile): {np.percentile(data, 25)}")
print(f"Third Quartile (75th Percentile): {np.percentile(data, 75)}")


10th Percentile: 106.10000000000001
50th Percentile (Median): 508.0
90th Percentile: 904.2
First Quartile (25th Percentile): 188.25
Third Quartile (75th Percentile): 779.5


In [68]:
'''66. Create a NumPy array of integers and find the index of a specific element.'''
arr = np.array([10, 20, 30, 40, 50])
element = 30
print(np.where(arr == element))  # Output: (array([2]),)


(array([2]),)


In [69]:
'''67. Generate a random NumPy array and sort it in ascending order.'''
arr = np.random.randint(1, 101, 10)
print(np.sort(arr))  # Output: Sorted array


[ 1  1  2 12 20 25 28 85 86 96]


In [70]:
'''68. Filterelements >20  in the given NumPy array. arr = np.array([12, 25, 6, 42, 8, 30])'''
arr = np.array([12, 25, 6, 42, 8, 30])
print(arr[arr > 20])  # Output: [25 42 30]


[25 42 30]


In [71]:
'''69. Filter elements which are divisible by 3 from a given NumPy array. arr = np.array([1, 5, 8, 12, 15])'''
arr = np.array([1, 5, 8, 12, 15])
print(arr[arr % 3 == 0])  # Output: [12 15]


[12 15]


In [72]:
'''70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.  arr = np.array([10, 20, 30, 40, 50])'''
arr = np.array([10, 20, 30, 40, 50])
print(arr[(arr >= 20) & (arr <= 40)])  # Output: [20 30 40]



[20 30 40]


In [73]:
'''71. For the given NumPy array, check its byte order using the dtype attribute byteorder.  arr = np.array([1, 2, 3])'''
arr = np.array([1, 2, 3])
print(arr.dtype.byteorder)  # Output: '=' (native), '<' (little-endian), or '>' (big-endian)


=


In [74]:
'''72. For the given NumPy array, perform byte swapping in place using byteswap(). arr = np.array([1, 2, 3], dtype=np.int32)'''
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print("Byte-swapped array:", arr)


Byte-swapped array: [16777216 33554432 50331648]


In [75]:
'''73. For the given NumPy array, swap its byte order without modifying the original array using
newbyteorder(). arr = np.array([1, 2, 3], dtype=np.int32)'''
arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.newbyteorder()
print("Original array:", arr)
print("Byte-swapped array:", swapped_arr)


Original array: [1 2 3]
Byte-swapped array: [16777216 33554432 50331648]


In [76]:
'''74. For the given NumPy array and swap its byte order conditionally based on system endianness using
newbyteorder(). arr = np.array([1, 2, 3], dtype=np.int32)'''
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':  # Native endianness
    swapped_arr = arr.newbyteorder()
    print("Swapped array:", swapped_arr)
else:
    print("Byte swapping not required.")


Swapped array: [16777216 33554432 50331648]


In [77]:
'''75. For the given NumPy array, check if byte swapping is necessary for the current system using dtype
attribute byteorder. arr = np.array([1, 2, 3], dtype=np.int32)'''
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':
    print("Byte swapping may be necessary.")
else:
    print("No byte swapping needed.")


Byte swapping may be necessary.


In [78]:
'''76. Create a NumPy array arr1 with values from 1 to 10. Create a copy of arr1 named copy_arr and modify
an element in copy_arr. Check if modifying copy_arr affects arr1.'''
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 99
print("Original array:", arr1)
print("Modified copy:", copy_arr)


Original array: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy: [99  2  3  4  5  6  7  8  9 10]


In [79]:
'''77. Create a 2D NumPy array matrix of shape (3, 3) with random integers. Extract a slice view_slice from
the matrix. Modify an element in view_slice and observe if it changes the original matrix.'''
matrix = np.random.randint(1, 10, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 99
print("Original matrix:", matrix)
print("View slice:", view_slice)


Original matrix: [[99  9  7]
 [ 3  2  1]
 [ 8  3  5]]
View slice: [[99  9]
 [ 3  2]]


In [80]:
'''78. Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
view_b from array_a and broadcast the addition of 5 to view_b. Check if it alters the original array_a.'''
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[1:3, :]
view_b += 5
print("Original array after modification:", array_a)
print("Modified slice:", view_b)


Original array after modification: [[ 1  2  3]
 [ 9 10 11]
 [12 13 14]
 [10 11 12]]
Modified slice: [[ 9 10 11]
 [12 13 14]]


In [81]:
'''79. Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8. Create a reshaped view
reshaped_view of shape (4, 2) from orig_array. Modify an element in reshaped_view and check if it
reflects changes in the original orig_array.'''
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 99
print("Original array:", orig_array)
print("Reshaped view:", reshaped_view)


Original array: [[99  2  3  4]
 [ 5  6  7  8]]
Reshaped view: [[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


In [82]:
'''80. Create a NumPy array data of shape (3, 4) with random integers. Extract a copy data_copy of
elements greater than 5. Modify an element in data_copy and verify if it affects the original data.'''
data = np.random.randint(1, 10, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 99
print("Original data:", data)
print("Modified copy:", data_copy)


Original data: [[2 7 6 7]
 [1 8 8 6]
 [5 9 7 1]]
Modified copy: [99  6  7  8  8  6  9  7]


In [83]:
'''81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.'''
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition:\n", A + B)
print("Subtraction:\n", A - B)


Matrix A:
 [[5 7 1]
 [2 8 2]
 [5 9 5]]
Matrix B:
 [[3 7 3]
 [3 3 5]
 [7 7 4]]
Addition:
 [[ 8 14  4]
 [ 5 11  7]
 [12 16  9]]
Subtraction:
 [[ 2  0 -2]
 [-1  5 -3]
 [-2  2  1]]


In [84]:
'''82. Generate two matrices C (3x2) and D (2x4) and perform matrix multiplication.'''
C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))
result = np.dot(C, D)
print("Matrix C:\n", C)
print("Matrix D:\n", D)
print("Matrix multiplication result:\n", result)


Matrix C:
 [[9 5]
 [4 1]
 [7 3]]
Matrix D:
 [[2 8 9 3]
 [4 5 4 5]]
Matrix multiplication result:
 [[ 38  97 101  52]
 [ 12  37  40  17]
 [ 26  71  75  36]]


In [85]:
'''83. Create a matrix E and find its transpose.'''
E = np.random.randint(1, 10, size=(3, 4))
transpose = E.T
print("Matrix E:\n", E)
print("Transpose of E:\n", transpose)


Matrix E:
 [[5 6 2 2]
 [3 1 7 3]
 [6 7 4 6]]
Transpose of E:
 [[5 3 6]
 [6 1 7]
 [2 7 4]
 [2 3 6]]


In [86]:
'''84. Generate a square matrix F and compute its determinant.'''
from numpy.linalg import det

F = np.random.randint(1, 10, size=(3, 3))
determinant = det(F)
print("Matrix F:\n", F)
print("Determinant of F:", determinant)


Matrix F:
 [[3 3 6]
 [2 4 8]
 [3 1 4]]
Determinant of F: 12.0


In [ ]:
'''85. Create a square matrix G and find its inverse'''
from numpy.linalg import inv

G = np.random.randint(1, 10, size=(3, 3))
if det(G) != 0:
    inverse = inv(G)
    print("Matrix G:\n", G)
    print("Inverse of G:\n", inverse)
else:
    print("Matrix G is singular, so it does not have an inverse.")
